services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI port
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres 
    restart: unless-stopped
     

