services:
  rabbitmq:
    # build: .
    image: iot-rabbitmq
    container_name: iot-rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI port
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: iot-timescaledb-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=iot
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: iot-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

  sensor-simulation:
    depends_on:
      - rabbitmq
      - timescaledb
    build:
      context: .          
      dockerfile: ./cmd/sensor-simulation/Dockerfile
    container_name: iot-sensor-simulation-1
    environment:
      - SENSOR_SERIAL_NUMBER=AAD-1123
      - SENSOR_SAMPLE_FREQUENCY=1.0

