services:
  rabbitmq:
    build: dependencies/rabbitmq/
    container_name: iot-rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI port

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: iot-timescaledb-1
    depends_on:
      - rabbitmq
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=iot
  
  grafana:
    image: grafana/grafana:latest
    container_name: iot-grafana
    depends_on:
      - timescaledb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
  
  sensor-simulation:
    depends_on:
      - rabbitmq
      - timescaledb
      - sensor-registry
      - sensor-logs-ingester
      - sensor-measurements-ingester
    build:
      context: .          
      dockerfile: ./cmd/sensor-simulation/Dockerfile
    container_name: iot-sensor-simulation-1
    environment:
      - SENSOR_SERIAL_NUMBER=AAD-1123
      - SENSOR_SAMPLE_FREQUENCY=1.0
  
  iotctl:
    depends_on:
      - rabbitmq
      - timescaledb
      - sensor-simulation
    build:
      context: .          
      dockerfile: ./cmd/iotctl/Dockerfile
    container_name: iot-iotctl
  
  sensor-logs-ingester:
    depends_on:
      - rabbitmq
      - timescaledb
    build:
      context: .          
      dockerfile: ./cmd/sensor-logs-ingester/Dockerfile
    container_name: iot-sensor-logs-ingester
  
  sensor-measurements-ingester:
    depends_on:
      - rabbitmq
      - timescaledb
    build:
      context: .          
      dockerfile: ./cmd/sensor-measurements-ingester/Dockerfile
    container_name: iot-sensor-measurements-ingester
    restart: unless-stopped
  
  sensor-registry:
    depends_on:
      - rabbitmq
      - timescaledb
    build:
      context: .          
      dockerfile: ./cmd/sensor-registry/Dockerfile
    container_name: iot-sensor-registry
