{
 "title": "IoT",
 "time": { "from": "now-15s", "to": "now+20s" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "bucket_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "serial_number",
    "query": "SELECT serial_number FROM sensor"
   },
   {
    "name": "measurementQuery",
    "query": "select query from statements_history.queries\nwhere query ILIKE 'insert into sensor_measurement%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Acceleration $serial_number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT sensor_measurement.time, sensor_measurement.measurement, sensor.serial_number\r\nFROM sensor_measurement INNER JOIN sensor\r\n  ON sensor_measurement.sensor_id = sensor.id\r\nWHERE sensor.serial_number in ($serial_number)\r\nORDER BY time DESC \r\nLIMIT 100000"
    },
    {}
   ]
  },
  {
   "title": "Writes to Disk and Buffer Flushes",
   "type": "timeseries",
   "description": "Disk and buffer writes over time, broken down by:\n- writes_MBps – Total physical disk writes performed by PostgreSQL backends during query execution, as seen by the OS. This is the most accurate view of actual I/O load (from pg_stat_kcache.exec_writes).\n- shared_buffer_MBps – Data flushed from PostgreSQL’s shared buffer cache to disk. These are typically managed by checkpoints or the background writer.\n- local_buffer_MBps – Writes to local (non-shared) buffers, often related to unlogged or temporary tables. These are buffered but not part of shared memory.\n- temp_buffer_MBps – Buffer writes for temporary data during execution, such as sorting or hashing operations that spill to disk.\n- wal_generated_MBps – Volume of WAL (Write-Ahead Log) data generated. This doesn’t reflect immediate disk writes — WAL data is first written to memory and may be flushed asynchronously depending on parameters like wal_writer_delay and commit_delay.",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        created,\n        extract('epoch' from created - lag(d.created) OVER (w)) AS delta_seconds,\n        d.exec_writes - lag(d.exec_writes) OVER (w) AS delta_exec_writes,\n        d.shared_blks_written - lag(d.shared_blks_written) OVER (w) AS delta_shared_blks_written,\n        d.local_blks_written - lag(d.local_blks_written) OVER (w) AS delta_local_blks_written,\n        d.temp_blks_written - lag(d.temp_blks_written) OVER (w) AS delta_temp_blks_written,\n        d.wal_bytes - lag(d.wal_bytes) OVER (w) AS delta_wal_bytes,\n        stats_reset\n    FROM\n        statements_history.snapshots AS d\n    WHERE\n        created > now() - INTERVAL '2 hours'\n    WINDOW\n        w AS (PARTITION BY stats_reset ORDER BY created ASC)\n)\nSELECT\n    created AS \"time\",\n    delta_exec_writes / 1024 / 1024 / delta_seconds AS writes_MBps,\n    (delta_shared_blks_written * 8.0) / 1024 / delta_seconds AS shared_buffer_MBps,\n    (delta_local_blks_written * 8.0) / 1024 / delta_seconds AS local_buffer_MBps,\n    (delta_temp_blks_written * 8.0) / 1024 / delta_seconds AS temp_buffer_MBps,\n    delta_wal_bytes / 1024 / 1024 / delta_seconds AS wal_generated_MBps\nFROM\n    deltas\nORDER BY\n    created ASC;"
    }
   ]
  },
  {
   "title": "Average Latency per Query",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        st.created,\n        st.queryid,\n        st.rolname,\n        st.datname,\n        s.stats_reset,\n        q.query,\n        st.calls - lag(st.calls) OVER (query_w) AS delta_calls,\n        st.total_exec_time - lag(st.total_exec_time) OVER (query_w) AS delta_total_exec_time,\n        extract('epoch' from st.created - lag(st.created) OVER (query_w)) AS delta_seconds\n    FROM\n        statements_history.statements AS st\n    JOIN\n        statements_history.queries AS q USING (queryid, datname, rolname)\n    JOIN\n        statements_history.snapshots AS s USING (created)\n    WHERE\n        st.created > now() - interval '15 minutes'\n        AND st.created < now() + interval '15 minutes'\n        AND q.query ILIKE 'insert into sensor_measurement%'\n    WINDOW\n        query_w AS (PARTITION BY st.datname, st.rolname, st.queryid, s.stats_reset ORDER BY st.created)\n)\nSELECT\n    created AS \"time\",\n    query,\n    delta_total_exec_time / NULLIF(delta_calls, 0) / 1000 AS exec_time_per_query\nFROM\n    deltas\nWHERE\n    delta_calls > 0\nORDER BY\n    created ASC;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MB/query" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        st.created,\n        st.queryid,\n        st.rolname,\n        st.datname,\n        s.stats_reset,\n        q.query,\n        st.calls - lag(st.calls) OVER (query_w) AS delta_calls,\n        st.shared_blks_hit - lag(st.shared_blks_hit) OVER (query_w) AS delta_shared_blks_hit,\n        st.shared_blks_read - lag(st.shared_blks_read) OVER (query_w) AS delta_shared_blks_read,\n        extract('epoch' from st.created - lag(st.created) OVER (query_w)) AS delta_seconds\n    FROM\n        statements_history.statements AS st\n    JOIN\n        statements_history.queries AS q USING (queryid, datname, rolname)\n    JOIN\n        statements_history.snapshots AS s USING (created)\n    WHERE\n        st.created > now() - interval '15 minutes'\n        AND st.created < now() + interval '15 minutes'\n        AND q.query ILIKE 'insert into sensor_measurement%'\n    WINDOW\n        query_w AS (PARTITION BY st.datname, st.rolname, st.queryid, s.stats_reset ORDER BY st.created)\n)\nSELECT\n    created AS \"time\",\n    query,\n    delta_shared_blks_hit / NULLIF(delta_calls, 0) * 8.0 / 1024 AS cache_hit_per_query,\n    delta_shared_blks_read / NULLIF(delta_calls, 0) * 8.0 / 1024 AS cache_miss_per_query\nFROM\n    deltas\nWHERE\n    delta_calls > 0\nORDER BY\n    created ASC;\n"
    }
   ]
  },
  {
   "title": "'sensor_measurement' Table Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    created,\n    size\nFROM\n    hypertables_size_history.statements\nWHERE hypertable_name = 'sensor_measurement'; "
    }
   ]
  },
  {
   "title": "Average Inserted Rows Per Query",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        st.created,\n        st.queryid,\n        st.rolname,\n        st.datname,\n        s.stats_reset,\n        q.query,\n        st.calls - lag(st.calls) OVER (query_w) AS delta_calls,\n        st.rows - lag(st.rows) OVER (query_w) AS delta_rows\n    FROM\n        statements_history.statements AS st\n    JOIN\n        statements_history.queries AS q USING (queryid, datname, rolname)\n    JOIN\n        statements_history.snapshots AS s USING (created)\n    WHERE\n        st.created > now() - interval '15 minutes'\n        AND st.created < now() + interval '15 minutes'\n        AND q.query ILIKE 'insert into sensor_measurement%'\n    WINDOW\n        query_w AS (PARTITION BY st.datname, st.rolname, st.queryid, s.stats_reset ORDER BY st.created)\n)\nSELECT\n    created AS \"time\",\n    query,\n    delta_rows / NULLIF(delta_calls, 0) AS rows_per_query\nFROM\n    deltas\nWHERE\n    delta_calls > 0\nORDER BY\n    created ASC;\n"
    }
   ]
  },
  {
   "title": "Logs $serial_number",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{logger=\"$serial_number\"} |= ``"
    }
   ]
  }
 ]
}