name: cd

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "off"

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Test
      run: |
        make test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: "iferdel777/iot"
        install: true

    # - name: Build & Push with Docker Build-Push Action
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./cmd/sensor-simulation/Dockerfile
    #     push: true
    #     platforms: linux/amd64
    #     tags: |
    #       ${{ vars.DOCKERHUB_USERNAME }}/iot-sensor-simulation:${{ github.sha }}
    #     target: staging
    #     provenance: false # this allows the provenance to be created/managed by docker build cloud and not by this build-push-action

    - name: Build & Push Sensor Simulation
      if: contains(steps.changed.outputs.all_changed_files, 'cmd/sensor-simulation/')
      run: |
        SERVICE_VERSION=$(cat cmd/sensor-simulation/VERSION)
        docker buildx build \
        --platform linux/amd64 \
        --build-arg VERSION=$SERVICE_VERSION \
        --target staging \
        -f cmd/sensor-simulation/Dockerfile \
        -t ${{ vars.DOCKERHUB_USERNAME }}/iot-sensor-simulation:$SERVICE_VERSION \
        --push \
        .
